services:
  soloviov-demo-web-proxy:
    image: hordesalik/soloviov-demo-web-proxy:1.1.0
    hostname: soloviov-demo-web-proxy
    depends_on:
      - short-time-code
      - action-request
      - soloviov-demo-frontend
      - the-page-mongo-express
      - the-page-backend
      - the-page-frontend
    ports:
      - 80:80

  short-time-code:
    image: hordesalik/short-time-code:1.0.0
    hostname: short-time-code
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  action-request:
    image: hordesalik/action-request:1.0.0
    hostname: action-request
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80
      SHORT_TIME_CODE_API_ORIGIN: http://short-time-code:80

  soloviov-demo-frontend:
    image: hordesalik/soloviov-demo-frontend:1.1.0
    hostname: soloviov-demo-frontend
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  the-page-mongo:
    image: mongo:5.0.28
    hostname: the-page-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: the-page
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./mongo_data/db:/data/db
      - ./mongo_data/configdb:/data/configdb

  the-page-mongo-express:
    image: mongo-express:1.0.2
    hostname: the-page-mongo-express
    depends_on:
      - the-page-mongo
    restart: always
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://the-page-mongo:27017/
      ME_CONFIG_MONGODB_SERVER: the-page-mongo
      ME_CONFIG_MONGODB_HOST: the-page-mongo
      ME_CONFIG_SITE_BASEURL: /the-page-mongo-express/
      ME_CONFIG_BASICAUTH: "false"
      ME_CONFIG_BASICAUTH_FILE: /run/secrets/the_page_me_config_basicauth
      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/the_page_me_config_basicauth_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/the_page_me_config_basicauth_password
    secrets:
      - the_page_me_config_basicauth
      - the_page_me_config_basicauth_username
      - the_page_me_config_basicauth_password

  the-page-backend:
    image: hordesalik/the-page-backend:1.0.1
    hostname: the-page-backend
    depends_on:
      - the-page-mongo
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      MONGO_HEARTBEAT_FREQUENCY_MS: 30000
      JWT_SECRET_FILE: /run/secrets/the_page_backend_gwt_secret
      APP_BASE_PATH: /the-page-backend/
      FRONTEND_BASE_URL: /the-page-frontend
    secrets:
      - the_page_backend_gwt_secret
      - the_page_mongo_uri

  the-page-frontend:
    image: hordesalik/the-page-frontend:1.0.1
    hostname: the-page-frontend
    depends_on:
      - the-page-mongo
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      MONGO_HEARTBEAT_FREQUENCY_MS: 30000
      APP_BASE_HOSTNAME: thepage.local
    secrets:
      - the_page_mongo_uri

secrets:
  the_page_me_config_basicauth:
    external: true
  the_page_me_config_basicauth_username:
    external: true
  the_page_me_config_basicauth_password:
    external: true
  the_page_mongo_uri:
    external: true
  the_page_backend_gwt_secret:
    external: true
