services:
  soloviov-demo:
    hostname: soloviov-demo
    image: hordesalik/soloviov-demo:1.1.2
    ports:
      - 80:80

  short-time-code:
    hostname: short-time-code
    image: hordesalik/short-time-code:1.0.0
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  action-request:
    hostname: action-request
    image: hordesalik/action-request:1.0.0
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80
      SHORT_TIME_CODE_API_ORIGIN: http://short-time-code:80

  soloviov-demo-frontend:
    hostname: soloviov-demo-frontend
    image: hordesalik/soloviov-demo-frontend:1.0.0
    environment:
      NO_DOTENV: 1
      HTTP_SERVER_PORT: 80

  the-page-backend:
    hostname: the-page-backend
    image: hordesalik/the-page-backend:1.0.0
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      JWT_SECRET_FILE: /run/secrets/the_page_backend_gwt_secret
      APP_BASE_PATH: /the-page-backend/
      FRONTEND_BASE_URL: /the-page-frontend
    secrets:
      - the_page_backend_gwt_secret
      - the_page_mongo_uri

  the-page-frontend:
    hostname: the-page-frontend
    image: hordesalik/the-page-frontend:1.0.0
    environment:
      HTTP_SERVER_PORT: 80
      MONGO_URI_FILE: /run/secrets/the_page_mongo_uri
      APP_BASE_HOSTNAME: thepage.local
    secrets:
      - the_page_mongo_uri

secrets:
  the_page_mongo_uri:
    external: true
  the_page_backend_gwt_secret:
    external: true
